Repository owncloud/firstrunwizard, pull requests merged in 2019-04, with the labels that each got.

#96 Phpunit 5 6
  composer.lock
  phpunit.xml
  tests/lib/configtest.php
  tests/lib/utiltest.php
Labels: 4 - To release, QA-Team

#99 [stable10] drop php 5.6
  .drone.yml
  composer.json
  composer.lock
  phpunit.xml
  tests/lib/configtest.php
  tests/lib/utiltest.php
Labels: 3 - To Review, QA-Team

#103 Release 1.2.0
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3 - To Review
