Repository owncloud/firstrunwizard, pull requests merged in 2020-04, with the labels that each got.

#128 [Tests-Only] Update phpstan to latest version
  .drone.star
  lib/config.php
  phpstan.neon
  vendor-bin/phpstan/composer.json
Labels: 4 - To release, QA-Team

#129 Drop PHP 7.1
  .drone.star
  composer.json
  composer.lock
Labels: 3 - To Review, QA-Team

#132 [Tests-Only] Bump phan 2.7 & Run phan in CI
  .drone.star
  .phan/config.php
  vendor-bin/phan/composer.json
Labels: QA-Team

#133 [Tests-Only] Implement PHPunit v8
  .gitignore
  vendor-bin/behat/composer.json
Labels: 3 - To Review, QA-Team

#134 Adjust drone pipelines for PHP 7.4
  .drone.star
Labels: 3 - To Review, QA-Team
